Add support for changing the volume with the mouse wheel
dremin/RetroBar pull request #264
Opened 2022-03-01 01:29 UTC by xoascf

Change the volume by rolling the mouse wheel over the volume icon in the notification area.

_Maybe add it as a toggleable option, or change some things earlier by adding or using another ManagedShell function._

2022-03-04 06:04 UTC, dremin commented
I'm good with this being in RetroBar for now rather than ManagedShell since it sends the command to Explorer. We can move it to ManagedShell if/when the audio API is used for this.

2022-03-07 22:02 UTC, xoascf commented
> I'm good with this being in RetroBar for now rather than ManagedShell since it sends the command to Explorer. We can move it to ManagedShell if/when the audio API is used for this.

I was thinking of adding the list of missing APPCOMMAND constants and making public the default tray icon constants in ManagedShell, so they can be used here without having to define them again.

2022-03-10 04:54 UTC, dremin requested changes
I like the idea of moving the constants to ManagedShell but this is good for now, once the volume code is moved out of the UI code into a utility/helper class.

2022-03-10 04:54 UTC, dremin commented on RetroBar/Controls/NotifyIcon.xaml.cs
> +        }
Could you move this functionality out from the UserControl into a utility class?

2022-03-12 01:02 UTC, dremin approved these changes
🎉

2022-03-12 01:02 UTC, merged

2025-02-02 21:08 UTC, dremin commented
> Could we add the option to adjust the volume from anywhere in the system tray, rather than just over the volume icon? It's such a tiny target to aim for, where the system tray is easy to 'hit'.

That could break compatibility--any tray icon can potentially respond to the mouse wheel, and it wouldn't be great to break that functionality.

2025-02-02 22:18 UTC, xoascf commented
> Could we add the option to adjust the volume from anywhere in the system tray, rather than just over the volume icon? It's such a tiny target to aim for, where the system tray is easy to 'hit'.

There is a freeware software called Volume² that can help you with that: https://github.com/irzyxa/Volume2/releases