Added the option to show the start button on all displays
dremin/RetroBar pull request #628
Opened 2023-07-14 19:57 UTC by GreenJamesDev

The start menu itself still needs some work since it only opens on the primary display, however I still find this to be better than nothing as someone who uses two monitors.

2023-07-14 21:41 UTC, dremin requested changes
The only reason this isn’t currently in place is due to the start menu appearing on the incorrect display. If you’re able to address that part, I will gladly take a look!

2023-07-15 17:54 UTC, GreenJamesDev commented
Wow, I didn't realize just how locked off the start menu is from outside processes, haha. This is definitely going to require some out of the box methods to get working right if it's at all possible.

2023-07-15 22:11 UTC, xoascf commented
> Wow, I didn't realize just how locked off the start menu is from outside processes, haha. This is definitely going to require some out of the box methods to get working right if it's at all possible.

It is possible, but it may require you to detect which Start menu is opening and move it to the screen where the Start button was pressed, otherwise (if it was opened by pressing the Ctrl+Esc/Windows key), it should open the Start menu on the screen where the cursor is, and the button should appear as pressed only on the screen where it was opened.

In both cases, I think it would be convenient to move the Start menu window to the side of the taskbar when changing its edge, as happens in Windows 10 and earlier.

2023-07-16 01:18 UTC, dremin commented
If you’d like to tackle that, [this class](https://github.com/dremin/RetroBar/blob/master/RetroBar/Utilities/StartMenuMonitor.cs) would be a great place to start! It detects the start menu being open and its window handle.

2023-07-16 05:16 UTC, GreenJamesDev commented
Okay, I think I have an idea as to how this could work that I will test out in the morning.

2024-08-15 23:42 UTC, SketchNI commented
I built a copy of retrobar from this PR and the start menu opens on the correct monitor. 

However, I'm also using Start 11 which may explain that.

2024-10-16 23:40 UTC, Avid29 commented
> If you’d like to tackle that, [this class](https://github.com/dremin/RetroBar/blob/master/RetroBar/Utilities/StartMenuMonitor.cs) would be a great place to start! It detects the start menu being open and its window handle.

Surely there's a way to subscribe to this event rather than polling every 100ms, right?

2024-10-17 01:38 UTC, dremin commented
> > If you’d like to tackle that, [this class](https://github.com/dremin/RetroBar/blob/master/RetroBar/Utilities/StartMenuMonitor.cs) would be a great place to start! It detects the start menu being open and its window handle.
> 
> Surely there's a way to subscribe to this event rather than polling every 100ms, right?

I don't remember why I implemented it this way instead of using WinEvents...

2025-01-03 09:23 UTC, dremin commented
I am adding this with support for opening the Start menu on the correct monitor in #999.

2025-01-03 09:23 UTC, closed without merging