Fix non-integer scales
dremin/RetroBar pull request #738
Opened 2024-01-07 03:46 UTC by jarupxx

Fix incorrect sizing on non-integer scales https://github.com/dremin/RetroBar/issues/727

2024-01-07 22:20 UTC, dremin requested changes
I don't think this is the right fix-- we need to disable layout rounding for non-integer scales so that the rounding does not cause layout overflow. Also, why is the taskbar height increased?

2024-01-07 23:10 UTC, jarupxx commented
Disabling SetLayoutRounding() causes blurry icons. When it is enabled, the Quick Launch icon is missing, and I think the reason for this is that there is no margin in the layout. So I added the height of the taskbar.
Tested 125%,150%,175%.

2024-01-19 12:32 UTC, jarupxx commented
Please tell me. Which value in the theme should I change to adjust the gap at the bottom of the button?
![gap](https://github.com/dremin/RetroBar/assets/20138367/7622c464-d0f9-4b45-b559-5ee66eada5ca)

2025-01-08 01:34 UTC, dremin commented
Closing because this is not the correct fix. We need layout rounding for fractional DPI.

2025-01-08 01:34 UTC, closed without merging