Implement Explorer.exe monitoring feature.
dremin/RetroBar pull request #945
Opened 2024-11-11 14:28 UTC by MKKNinetyTwo

**Description:**
Implement Explorer.exe monitoring feature using TaskbarCreated event.

**What it does?**
If we detect that Explorer.exe has restarted we will call ReopenTaskbars.

**Why?**
This will ensure that when Explorer is restarted, RetroBar is also re-initialized.
This will fix stuff like wrong desktop size etc that would happen if we did not re-initialize RetroBar.

**Tests performed:**
Lots and lots of testing, on Windows 11 systems.

**What issues this should fix?**
@dremin PR https://github.com/cairoshell/ManagedShell/pull/113 fixed all of these:
https://github.com/dremin/RetroBar/issues/942
https://github.com/dremin/RetroBar/issues/938
https://github.com/dremin/RetroBar/issues/927
https://github.com/dremin/RetroBar/issues/648
https://github.com/dremin/RetroBar/issues/476
https://github.com/dremin/RetroBar/issues/457
so this PR is just a follow up now, this will fix some bugs like the desktop is not resized properly after Explorer is restarted etc.

2024-11-11 20:15 UTC, dremin commented
I'm not sure this is quite right--there could be several explorer.exe processes, how do we know we are looking at the current user's shell process and not, say, a file explorer window process?

2024-11-12 00:09 UTC, xoascf commented on RetroBar/Utilities/WindowManager.cs
> +        [DllImport("user32.dll")] private static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);
Both can be used from `ManagedShell.Interop.NativeMethods`.

2024-11-12 04:19 UTC, dremin commented
I'd like to try avoiding crashing Explorer altogether if possible. This commit prevents the crash for me: https://github.com/cairoshell/ManagedShell/commit/33dc8a3d07f4ba5423193be4b9980c71db2c6790

2024-11-12 05:03 UTC, dremin commented
Even with the Explorer crash fixed, we may still want something like what is in this PR so that we can restore the AppBar state and workarea after Explorer restarts. Without the Explorer crash, we can simplify things by listening for the `TaskbarCreated` message instead of having to detect a PID.

2024-11-14 06:42 UTC, dremin commented
Nice! A few comments:
- For the purposes of the monitor window, a `Form` is pretty heavy. Instead we should create a simple [NativeWindow](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.nativewindow?view=windowsdesktop-8.0), there are a few examples of this in the ManagedShell code if needed.
- The message for `TaskbarCreated` will never change, so as an optimization `RegisterWindowMessage` should only be called once rather than as part of the `WndProc`.
- You can import all of the pinvokes from `ManagedShell.Interop`, it should also have any constants needed.
- I don't think we need to restart RetroBar completely, instead calling `WindowManager.ReopenTaskbars()` should be sufficient.

2024-11-15 01:24 UTC, dremin requested changes
This looks great, thanks! Just a couple minor things to change and it will be good to go!

2024-11-15 01:24 UTC, dremin commented on RetroBar/Utilities/ExplorerMonitor.cs
> +            _explorerMonitorisMonitoring = true;
Instead of maintaining a bool, can we check that `_explorerMonitorWindow` is not null?

2024-11-15 01:24 UTC, dremin commented on RetroBar/Utilities/ExplorerMonitor.cs
> +                        Debug.WriteLine($"Error handling TaskbarCreated message on ExplorerMonitor: {ex.Message}");
Instead of `Debug.WriteLine()`, lets use `ShellLogger.Warning()`.

2024-11-15 02:52 UTC, dremin approved these changes
🎉

2024-11-15 02:52 UTC, merged

2024-11-16 01:17 UTC, xoascf commented
When `explorer.exe` crashed on Windows 11 at logon, it created two taskbars on the same screen (there is only one enabled) while using the same .exe (a single instance, but two taskbar windows), I don't recall this happening before this PR was merged. Could this change be related, @dremin?
![what](https://github.com/user-attachments/assets/69c53b78-7173-4f15-bd5a-909a141468bd)

2024-11-16 01:38 UTC, dremin commented
> When `explorer.exe` crashed on Windows 11 at logon, it created two taskbars on the same screen (there is only one enabled) while using the same .exe (a single instance, but two taskbar windows), I don't recall this happening before this PR was merged. Could this change be related, @dremin?
> 
> ![what](https://github.com/user-attachments/assets/69c53b78-7173-4f15-bd5a-909a141468bd)
> 
> 

Hm, it's definitely possible. How are you creating the crash at login with the current build?

2024-11-16 03:36 UTC, dremin commented
> > When `explorer.exe` crashed on Windows 11 at logon, it created two taskbars on the same screen (there is only one enabled) while using the same .exe (a single instance, but two taskbar windows), I don't recall this happening before this PR was merged. Could this change be related, @dremin?
> > ![what](https://private-user-images.githubusercontent.com/28744392/386806549-69c53b78-7173-4f15-bd5a-909a141468bd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MjgxMTgsIm5iZiI6MTczMTcyNzgxOCwicGF0aCI6Ii8yODc0NDM5Mi8zODY4MDY1NDktNjljNTNiNzgtNzE3My00ZjE1LWJkNWEtOTA5YTE0MTQ2OGJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDAzMzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZjc4Yzc5YzcwMDdmMjY4NTdmYTE4NDhlZTc1ZTQzNTU1MTIyZWI3ZTMzYWQxZTI0NWM4ZWJhNjYyZGY3ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jduCFe4UcTW-EYHqvMlP9ggOByU0UuSkuA-KQTPcZr8)
> 
> Hm, it's definitely possible. How are you creating the crash at login with the current build?

@xoascf I noticed a potential race. Could you see if it is fixed with the `consistent-singleton-init` branch?

2024-11-16 06:52 UTC, dremin commented
@MKKNinetyTwo does it still happen if you move `_explorerMonitor.ExplorerMonitorStart(this);` after `openTaskbars();`?

2024-11-19 01:03 UTC, xoascf commented
Thanks, I happened to reproduce the crash twice, didn't have time to test and report back, that and `explorer.exe` fixed itself after a reboot. If this had been released earlier without the fix, it would have caused a lot of headaches! 😬

2024-11-20 05:59 UTC, xoascf commented
> It should now be fixed by #951.

Somehow I managed to trigger it again (this time on Windows 10) after disabling Game Mode on a Samsung Smart TV (which stretched the resolution from 2560x1440 at 100% to 4K at 150%). I'm currently using the latest commit: https://github.com/dremin/RetroBar/commit/97392db72c55a7ae3599e181bcbba3387cc51531.
<img width="520" alt="hmm" src="https://github.com/user-attachments/assets/a78d0ee9-23ca-4abe-8335-fbf9421d403b">

2024-11-20 06:02 UTC, dremin commented
> > It should now be fixed by #951.
> 
> Somehow I managed to trigger it again (this time on Windows 10) after disabling Game Mode on a Samsung Smart TV (which stretched the resolution from 2560x1440 at 100% to 4K at 150%). I'm currently using the latest commit: [97392db](https://github.com/dremin/RetroBar/commit/97392db72c55a7ae3599e181bcbba3387cc51531). <img alt="hmm" width="520" src="https://private-user-images.githubusercontent.com/28744392/387955686-a78d0ee9-23ca-4abe-8335-fbf9421d403b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODI3MjksIm5iZiI6MTczMjA4MjQyOSwicGF0aCI6Ii8yODc0NDM5Mi8zODc5NTU2ODYtYTc4ZDBlZTktMjNjYS00YWJlLTgzMzUtZmJmOTQyMWQ0MDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA2MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjkxMjMxMTc0MmY2NmU1MGFjYmM3MjQ3ZTU3Y2VjM2NmOTcwOWRhZDAxZTk1MjdjYWRhNzdlNmRiNzZkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.djfgr77SHRojgIk8_nfP_QeZ5NLjUaPrbY_MjNuHanE">

Does this consistently reproduce that way? Does it happen before this PR?

2024-11-20 06:22 UTC, xoascf commented
> Does this consistently reproduce that way? Does it happen before this PR?

No, it only happens just before this PR.
<details>
  <summary>Screenshots</summary>

Before merging PR #945 (commit https://github.com/dremin/RetroBar/commit/3be4280ba73084149984a4d2082d5689fafca034):
![bmtpr](https://github.com/user-attachments/assets/bd3c92ab-dde4-498d-b697-567209393f1f)


Just after merging PR #945 (commit https://github.com/dremin/RetroBar/commit/f52ab9c39b1b0e3e2436d64533a65c7b59c90e26):
![jamt](https://github.com/user-attachments/assets/bb8c2bba-bc1e-4fa0-a169-748b1231a34b)

</details>

2024-11-20 06:31 UTC, dremin commented
@xoascf On my system, changing the monitor scale triggers the TaskbarCreated message, but it doesn't give me the double taskbars. If you change your monitor scale only, does that trigger the issue?

2024-11-20 06:36 UTC, xoascf commented
@dremin Changing the monitor scale does not trigger the double taskbars (at least for commit https://github.com/dremin/RetroBar/commit/f52ab9c39b1b0e3e2436d64533a65c7b59c90e26).

2024-11-20 06:39 UTC, dremin commented
@xoascf Okay cool, so I think this is just another race with `NotifyDisplayChange` this time. I pushed a branch `fix-reopen-race` that adds a lock. Could you please see if it is fixed in that branch?

2024-11-20 06:58 UTC, dremin commented
@xoascf Could you please enable debug logging, then reproduce the double taskbar issue, and provide the logs?

2024-11-20 07:16 UTC, xoascf commented
> @xoascf Could you please enable debug logging, then reproduce the double taskbar issue, and provide the logs?

@dremin, here is the log file when reproducing that issue for commit [1733883](https://github.com/dremin/RetroBar/commit/1733883499283990a1ec512a29f056fccadd109d): [2024-11-20_020735924.log](https://github.com/user-attachments/files/17826588/2024-11-20_020735924.log)

2024-11-20 07:36 UTC, dremin commented
> > @xoascf Could you please enable debug logging, then reproduce the double taskbar issue, and provide the logs?
> 
> @dremin, here is the log file when reproducing that issue for commit [1733883](https://github.com/dremin/RetroBar/commit/1733883499283990a1ec512a29f056fccadd109d): [2024-11-20_020735924.log](https://github.com/user-attachments/files/17826588/2024-11-20_020735924.log)

@xoascf Thanks! I just pushed another commit to the fix-reopen-race branch. Could you please try it?